### ISSUE TITLE
Mis-paired doors.

### ISSUE THREAD

**Issue by Endermanbugzjfc** [KRUNCHSHooT/EasyDoor#1]
In the video: I had placed a pair of doors. Then, I placed a door next to another one, in which they face the same direction.

When I opened the newly placed door, these two "unpaired" doors were opening together. I expect only the newly placed door would open.

PM discord message link: https://discord.com/channels/373199722573201408/419876965986729984/1065554262857363486
Video file link: https://cdn.discordapp.com/attachments/419876965986729984/1065554262450524253/vcompress_8.mov

**Comment by KRUNCHSHooT** [comment]
I just realized it and i just fixed this bug.

thanks for reporting!
